version: '3.8'

services:
  web:
    container_name: web
    build: ./web
    volumes:
      - ./../public:/var/www/public:delegated
    restart: always
    ports:
      - "9081:80"
    tty: true

  mysql:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  memcache:
    build: ./memcache
    restart: always
    ports:
      - "11222:11211"
    tty: true

volumes:
    db_data: {}
